float:
  any:
  - base_args: ['@metric', '@dimension']
    constructor: LanceIVF
    disabled: false
    docker_tag: ann-benchmarks-lance
    module: ann_benchmarks.algorithms.lance
    name: lance-ivf
    run_groups:
      IVFPQ:
        args:
          quantization: ['PQ',
#           'FLAT',
            ]
#         num_partitions: [256] # rows^1/2
#         num_sub_vectors: [96] # vector dimension count / 16
#         num_bits: [4, 8]      # 8
  - base_args: ['@metric', '@dimension']
    constructor: LanceHNSW
    disabled: true
    docker_tag: ann-benchmarks-lance
    module: ann_benchmarks.algorithms.lance
    name: lance-hnsw
    run_groups:
      HNSW:
        args:
         quantization: ['PQ',
#          'SQ',
           ]
#        m: [5, 48]
#        ef_construction: [150, 300, 500]
