float:
  any:
  - base_args: ['@metric']
    constructor: LanceIVF
    disabled: false
    docker_tag: ann-benchmarks-lance
    module: ann_benchmarks.algorithms.lance
    name: lance-ivf
    run_groups:
      IVF:
        args:
          quantization: [
            'PQ',
#           'FLAT',
            ]
          num_partitions: [
#           256, 512, 1024,
            1000
            ] # rows^1/2
          num_sub_vectors: [
            128,
#           96, 192, 480,
#            960
            ] # vector dimension count / 16
          num_bits: [
#           4,
            8,
            ] # 8
  - base_args: ['@metric']
    constructor: LanceHNSW
    disabled: false
    docker_tag: ann-benchmarks-lance
    module: ann_benchmarks.algorithms.lance
    name: lance-hnsw
    run_groups:
      HNSW:
        args:
          quantization: [
#          'PQ',
           'SQ',
            ]
          m: [
            5,
#            48,
            ]
          ef_construction: [
            150,
#            300, 500,
            ]
        query_args: [
          [ # nprobes
          20,
          ], # 20
          [ # refine_factor
          None,
          ], # None
          ]
